- lib/preview/link.js
https://jira.ets.berkeley.edu/jira/browse/COL-549
> COL-549 Mark Portfolium entry URLs as not embeddable

- lib/preview/link.js
https://jira.ets.berkeley.edu/jira/browse/COL-579
> COL-579 Update user agent string for link previews

- lib/preview/link.js
https://jira.ets.berkeley.edu/jira/browse/COL-576
> COL-576 Special handling for Vimeo URLs

- buildspec.yml
https://jira.ets.berkeley.edu/jira/browse/COL-639
See http://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
> COL-639, build file (YAML) for AWS CodeBuild flow

- buildspec.yml
https://jira.ets.berkeley.edu/jira/browse/COL-639
* gulp is not in PATH, as I should have known
* Let's keep artifact name brain-dead-simple until fanciness is needed.
> COL-639, explicit path ref to gulp

- lib/preview/link.js
Also includes improvements to small thumbnail generation. See https://jira.ets.berkeley.edu/jira/browse/COL-669 for details.
> COL-669 Include large image in YouTube preview generation

- lib/preview/image.js
https://jira.ets.berkeley.edu/jira/browse/COL-432
https://jira.ets.berkeley.edu/jira/browse/COL-664
> COL-432 COL-664 Handle previews for animated GIFs

- package.json
Related: https://github.com/ets-berkeley-edu/suitec/pull/292
> NOJIRA, set master branch to version 1.1.0

- config/production.json
The currently published configs don't work anywhere, but let's not give people ideas.
> NOJIRA Flag bogus production config as truly bogus

- lib/preview/video.js
https://jira.ets.berkeley.edu/jira/browse/COL-679
`w=1` may be helpful for review.
> COL-679 Pull preview images from middle of video clips

- lib/preview/video.js
https://jira.ets.berkeley.edu/jira/browse/COL-679
QA version of #22.
> [QA] COL-679 Pull preview images from middle of video clips

- buildspec.yml
https://jira.ets.berkeley.edu/jira/browse/COL-685
master PR is #25
> [QA] COL-685, preview-service buildspec.yml gets proper role and ComputeType

- .ebextensions/00_ami.config
- .ebextensions/01_install_ghostscript.config
- .ebextensions/02_install_libreoffice.config
- .ebextensions/03_install_phantomjs.config
- .ebextensions/04_install_ffmpeg.config
https://jira.ets.berkeley.edu/jira/browse/COL-684
Files have been placed under `suitec-preview-service/dependencies` in our Elastic Beanstalk bucket.
> COL-684 Source non-packaged preview service dependencies from S3

- .ebextensions/00_ami.config
- .ebextensions/01_install_ghostscript.config
- .ebextensions/02_install_libreoffice.config
- .ebextensions/03_install_phantomjs.config
- .ebextensions/04_install_ffmpeg.config
https://jira.ets.berkeley.edu/jira/browse/COL-684
QA version of #27.
> [QA] COL-684 Source non-packaged preview service dependencies from S3

- lib/preview/image.js
- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-749
https://jira.ets.berkeley.edu/jira/browse/COL-751
Tested on suitec-preview-service-dev > suitec-dev > ucberkeley.beta.
> COL-749 COL-751 Preprocess SVG images to PNG

- .ebextensions/30_download_local_configurations.config
- .ebextensions/31_extract_local_configuration.config
https://jira.ets.berkeley.edu/jira/browse/COL-1014
Preview-service equivalent to https://github.com/ets-berkeley-edu/suitec/pull/588.
> COL-1014 Download local configurations from dedicated bucket

- .gitignore
- scripts/start-fake-services.sh
- scripts/stop-fake-services.sh
https://jira.ets.berkeley.edu/jira/browse/COL-560
Scripts I've been using for recent S3 work are here, tidied up a bit.  
Developer doc updated: https://docs.google.com/document/d/1QsOf7oBJMn8nX1XMEOiJEwGtiAFKlPFSqQOANK4fglk/edit
> COL-560, start/stop fake services for local dev of preview-service

- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1102
> COL-1102, update package deps of preview-service; notably aws-sdk

- .travis.yml
- gulpfile.js
- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1141
> COL-1141, Travis builds for preview-service

- .eslintrc.yml
- gulpfile.js
- lib/preview/image.js
- lib/preview/link.js
- lib/queue/api.js
- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1135
The last bit of ESLint work.
> COL-1135, add eslint rules; npm test support; minor fixes

- lib/core/storage.js
- lib/core/util.js
https://jira.ets.berkeley.edu/jira/browse/COL-1146
This will allow SuiteC to pass along s3 URIs (as stored in suitec db) which include bucket and objectKey info.
> COL-1146, preview-service can handle standard S3 URIs of format: s3://my-bucket/my-object-key

- config/default.json
- config/development.json
- config/production.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1151
`bucket..name` is intentionally invalid. See http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html
> COL-1151, remove obsolete/confusing configs (eg, region: us-west-1)

- lib/rest/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-1134
Create basic status and version endpoints matching the main SuiteC app. No authentication required.
> COL-1134 Status and version endpoints

- .ebextensions/10_create_apache_conf.config
https://jira.ets.berkeley.edu/jira/browse/COL-1134
> COL-1134 Apache config change for version and status endpoints

- package.json
> [QA] NOJIRA, preview-service qa branch to v1.2

- package.json
> NOJIRA, preview-service master branch to v1.3

- .ebextensions/01_install_ghostscript.config
- .ebextensions/02_install_libreoffice.config
- .ebextensions/03_install_phantomjs.config
- .ebextensions/04_install_ffmpeg.config
https://jira.ets.berkeley.edu/jira/browse/COL-1150
ebextensions fixed to work with amazon linux >= 4.2.0
> COL-1150 Preview service hangs during Elastic Beanstalk build

- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1201
https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md
> COL-1201, upgrade aws-sdk to 2.124.0

- buildspec.yml
- lib/rest/api.js
- scripts/generate-build-stats.sh
https://jira.ets.berkeley.edu/jira/browse/COL-1219
> COL-1219 Add artifact and commit info to /api/version

- README.md
- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1368
> COL-1368, test travis-ci.com migration with simple Lodash upgrade

- LICENSE
- app.js
- gulpfile.js
- lib/core/logger.js
- lib/core/storage.js
- lib/core/util.js
- lib/preview/api.js
- lib/preview/constants.js
- lib/preview/image.js
- lib/preview/link.js
- lib/preview/model.js
- lib/preview/office.js
- lib/preview/pdf.js
- lib/preview/video.js
- lib/queue/api.js
- lib/queue/model.js
- lib/rest/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-1408
Related to https://github.com/ets-berkeley-edu/suitec/pull/782
> COL-1408, Copyright ©2020 (preview-service)

- .ebextensions/20_set_node_environment.config
https://jira.ets.berkeley.edu/jira/browse/COL-1435
> COL-1435 Force node symlinks to hit the right versions

- lib/preview/api.js
- process.js
https://jira.ets.berkeley.edu/jira/browse/COL-1651
Sunlight is the best disinfectant.
> COL-1651 Get some initial debug logging on preview subprocess

- lib/preview/api.js
- lib/preview/office.js
- lib/queue/api.js
- process.js
https://jira.ets.berkeley.edu/jira/browse/COL-1651
> COL-1651 More debug logging

- lib/core/util.js
- lib/preview/office.js
- lib/queue/api.js
https://jira.ets.berkeley.edu/jira/browse/COL-1651
> COL-1651 It wasn't permissions, it was this libreoffice HOME dir nonsense

- lib/preview/link.js
https://jira.ets.berkeley.edu/jira/browse/COL-1667
> COL-1667 Preview handling for Google Jamboard URLs

- lib/preview/link.js
https://jira.ets.berkeley.edu/jira/browse/COL-1670
> COL-1670 Ignore custom embedURL for Google Docs presentations

- lib/preview/link.js
https://jira.ets.berkeley.edu/jira/browse/COL-1670
> COL-1670 Special embed handling for Google Docs presentations

- package-lock.json
- package.json
https://jira.ets.berkeley.edu/jira/browse/COL-1681
> COL-1681 npm dependency updates

- .ebextensions/00_ami.config
- .platform/hooks/predeploy/00_install_ghostscript.sh
- .platform/hooks/predeploy/01_install_libreoffice.sh
- .platform/hooks/predeploy/03_install_ffmpeg.sh
https://jira-secure.berkeley.edu/browse/COL-2208
> COL-2208 Update versions on supplemental packages

- deploy/start.sh
- deploy/stop.sh
- package-lock.json
- package.json
https://jira-secure.berkeley.edu/browse/COL-2208
forever relies on a bunch of outdated packages, and Elastic Beanstalk itself seems to handle daemonization just fine these days.
> COL-2208 Remove forever dependency
